img_size: 384
output: '/opt/ml/runs/exp' #path to output folder
num_class: 80
pretrained: False
optim: "AdamW"

# loss
eps: "1e-5"
dtgfl: False
gamma_pos: 0
gamma_neg: 2
loss_dev: -1
lr: 0.1
wd: 1e-2
ema-decay: 0.9997
ema-epoch: 0


# * Transformer
enc_layers: 1
dec_layers: 2
dim_feedforward: 4096
hidden_dim: 1024
dropout: 0.1
nheads: 4
position_embedding: 'sine'
backbone: 'CvT_w24'
pre_norm: False

