seed: 1004
epochs: 20
batch_size: 45
workers: 2
model: "multihead"  
lr: 1e-4
criterion: "cross_entropy"
log_interval: 20
schedule: False
name: "multi-head_celoss_fulltrain"
augmentation: False

optimizer: "adam"
weight_decay: 1e-5
momentum: 0.9
amsgrad: False
scheduler: None
poly_exp: 1.0
T_max: 10
eta_min: 0
step_size: 10
gamma: 0.1


train_path: "/opt/ml/finalproject/data/train/full_train.json"
val_path:   "/opt/ml/finalproject/data/eval/eval.json"
image_path: "/opt/ml/finalproject/data/"
model_dir: "./runs"

wandb: True
entity: cider6
project: "final_project"
