seed: 1004
epochs: 1
batch_size: 10
workers: 1
model: "ResNet101"
lr: 1e-4
criterion: "cross_entropy"
log_interval: 20
schedule: False
name: "epoch50_add_layer"

optimizer: "adam"
weight_decay: 1e-5
momentum: 0.9
amsgrad: False
scheduler: "lambda"
poly_exp: 1.0
T_max: 10
eta_min: 0
step_size: 10
gamma: 0.1

# train_path: "/opt/ml/finalproject/data/train/cat_sample_modified_train_dummy.json"
train_path: "/opt/ml/finalproject/data/train/jiyoon_resampled_errordel_train.json"
val_path:   "/opt/ml/finalproject/data/eval/cat_remodified_eval_dummy.json"
train_image_path: "/opt/ml/finalproject/data/train"
val_image_path: "/opt/ml/finalproject/data/eval"
model_dir: "./runs"

wandb: False
entity: cider6
project: "final_project"
