seed: 1004
epochs: 1
batch_size: 45
workers: 1
model: "ResNet101"
lr: 1e-4
criterion: "cross_entropy"
log_interval: 20
name: "for 1epoch pth"
schedule: False

optimizer: "adam"
weight_decay: 1e-5
momentum: 0.9
amsgrad: False
scheduler: "lambda"
poly_exp: 1.0
T_max: 10
eta_min: 0
step_size: 10
gamma: 0.1

train_path: "/opt/ml/finalproject/data/train/sample_modified_train_dummy.json"
val_path:   "/opt/ml/finalproject/data/eval/remodified_eval_dummy.json"
image_path: "/opt/ml/finalproject/data/"
model_dir: "./runs"

wandb: True
entity: cider6
project: "final_project"
