seed: 1004
epochs: 10
batch_size: 40
workers: 1
model: "ResNet101"
lr: 1e-3
criterion: "cross_entropy"
log_interval: 20
schedule: False
name: "newmetric"

optimizer: "adam"
weight_decay: 1e-5
momentum: 0.9
amsgrad: False
scheduler: None
poly_exp: 1.0
T_max: 10
eta_min: 0
step_size: 10
gamma: 0.1

train_path: "/opt/ml/finalproject/data/sampled/sampled_train.json"
val_path:   "/opt/ml/finalproject/data/eval/eval.json"
image_path: "/opt/ml/finalproject/data/"
model_dir: "./runs"

wandb: True
entity: cider6
project: "metric_test"
